Advantage Normalization: 0
Batch Size: 4096
Buffer Size: 16384
Clip: 0.2
Dual Clip: null
Entropy Coefficient: 0.0
Epoch: 3000
Epsilon Clip: 0.15
GAE Lambda: 0.95
Gamma: 0.99
Initial Sigma: -2.2
Learning Rate: 0.0001
Learning Rate Decay: true
Max Grad Norm: 0.5
Recompute Advantage: 1
Repeat/Collect: 10
Reward Nomalization: true
Step/Collect: 8192
Step/Epoch: 500000
Test Envs: 8
Training Envs: 64
Value Clip: 0
Value Coefficient: 0.25
